"""initial_schema

Revision ID: 48f9a1171568
Revises: 
Create Date: 2026-03-08 17:56:44.318452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f9a1171568'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('con_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('multiplier', sa.String(length=10), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('system_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Enum('CATASTROPHIC', 'WARNING', name='alertseverity'), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_heartbeats',
    sa.Column('process', sa.String(length=10), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('process')
    )
    op.create_table('trade_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PARTIAL', name='tradestatus'), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('ib_order_id', sa.String(length=50), nullable=True),
    sa.Column('leg_type', sa.Enum('ENTRY', 'PROFIT_TAKER', 'STOP_LOSS', 'CLOSE', name='legtype'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('security_type', sa.Enum('STK', 'ETF', 'OPT', 'FUT', name='securitytype'), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=True),
    sa.Column('strike', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('right', sa.String(length=4), nullable=True),
    sa.Column('qty_requested', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_filled', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('price_placed', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('avg_fill_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('profit_taker_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('profit_taker_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stop_loss_requested', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'REPRICING', 'AMENDING', 'FILLED', 'PARTIAL', 'CANCELED', 'ABANDONED', 'CLOSED_MANUAL', 'CLOSED_EXTERNAL', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('last_amended_at', sa.DateTime(), nullable=True),
    sa.Column('raw_ib_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reprice_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ask', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amendment_confirmed', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reprice_events')
    op.drop_table('orders')
    op.drop_table('metrics')
    op.drop_table('trade_groups')
    op.drop_table('system_heartbeats')
    op.drop_table('system_alerts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
