"""add market_price to position_cache

Revision ID: a504a55d11e7
Revises: 28646b547eeb
Create Date: 2026-03-23 08:10:05.207022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a504a55d11e7'
down_revision: Union[str, Sequence[str], None] = '28646b547eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_cache', sa.Column('market_price', sa.Numeric(precision=18, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_cache', 'market_price')
    # ### end Alembic commands ###
